### ISSUE TITLE
Add ability to not throw RuntimeException just return 'false' on decipherer failure

### ISSUE THREAD

**Issue by crystaler4** [tuupola/branca-php#15]
First of all, nice job with Branca-php lib, now the "issue".

1. Branca-php uses error messages which cannot be translated. I cannot wrap them to translation function because they are hardcoded.
2. In my CMS, I set custom exception_handler [When exception is thrown, user only see message "Please report error with IDxxxxx" and the error is saved to DB]. In case of Branca's decipherer failure I want to display some better message to user, which I cannot thanks to my custom exception_handler.

This is the question:

**Can you add config which disables RuntimeExceptions and just returns 'false' when decipherer operation fails?** Something like:

`$branca = new Branca( "supersecretkeyyoushouldnotcommit", false );`

This solves both points.

**Comment by tuupola** [comment]
For first point usual way would be to throw specialised exceptions. This way the user can catch named exceptions to figure out which action to take. This is a good idea and I probably should add them.

```php
class InvalidTokenVersionException extends RunTimeException {};
class ExpiredTokenException extends RunTimeException {};
class InvalidTokenException extends RunTimeException {};
```

For second point exceptions are quite normal way of handling errors. If your CMS especially requires methods to return `false` on failure, you could create a wrapper class which catches the exceptions and returns `false` instead.

**Comment by crystaler4** [comment]
To point 1: Ideally allow to set programmer own error messages

> For second point exceptions are quite normal way of handling errors. If your CMS especially requires methods to return false on failure, you could create a wrapper class which catches the exceptions and returns false instead.

I did not know this, thank you.
