### ISSUE TITLE
64-bit format codes are not available for 32-bit versions of PHP

### ISSUE THREAD

**Issue by tigerwill90** [tuupola/branca-php#2]
Dear Tuupola,

First of all, thank you for all your great work. I'm currently implementing a REST api using branca-middleware. I haven't touched my code since one month and I experienced an issue with sodium_compat library. I assume it's not an issue with Branca library but I'm just curious about this change.

Apparently, we need a 64 bit version of php to encode payload. Here is the error message than occur when I try to encode payload :

`pack(): 64-bit format codes are not available for 32-bit versions of PHP`

E:\Utilisateurs\Dropbox\brancatest\vendor\paragonie\sodium_compat\src\Core\Util.php:656
E:\Utilisateurs\Dropbox\brancatest\vendor\paragonie\sodium_compat\src\Crypto32.php:298
E:\Utilisateurs\Dropbox\brancatest\vendor\paragonie\sodium_compat\src\Crypto32.php:362
E:\Utilisateurs\Dropbox\brancatest\vendor\paragonie\sodium_compat\src\Compat.php:732
E:\Utilisateurs\Dropbox\brancatest\vendor\tuupola\branca\src\Branca.php:55

I have build a minimalistic test to reproduce this issue/change : 
[Error test](https://github.com/tigerwill90/brancatest)

I'm currently learning php, so I probably miss something relevant.

64-bit versions of PHP is now required to work with Branca ?

**Comment by tuupola** [comment]
Looking [at the code](https://github.com/paragonie/sodium_compat/blob/master/src/Core/Util.php#L654-L658) if php version is newer than 5.6.3 `sodium_compat` uses `pack("P", $int)` where `P` means 64 bit unsigned long long.  Looking at the logs this changes was done in [january 12](https://github.com/paragonie/sodium_compat/commit/15cfc2a2a99a153a8b84ebc5b930618c4f442d4b).

I haven't used 32-bit operating systems nor PHP for a while, but I guess you could manually install  older version of `paragonie/sodium_compat` to see if it fixes the problem.

```
$ composer require paragonie/sodium_compat:v1.5.3
```

**Comment by tigerwill90** [comment]
Thanks you for responding so quickly.

I can confirm you than downgrading `sodium_compat` from `v.1.5.5` to `v.1.5.3` actually solving the issue. I'm developing on windows with XAMPP who only support 32 bit version of php.

I also found and interesting answer [about 64-bit integer on windows](https://stackoverflow.com/a/3233881/9288564). 

> Note that PHP on Windows does not support 64-bit integers at all, even if both the hardware and PHP are 64-bit.

**Comment by paragonie-scott** [comment]
That note is only true for PHP before 7.0.

**Comment by paragonie-scott** [comment]
Version 1.5.6 fixes this issue.

**Comment by tuupola** [comment]
Thanks!

**Comment by tigerwill90** [comment]
Thanks
